
import "std/core.zc"
import "math.h" as c_math;

struct Math {}

impl Math {
    // Mathematical Constants
    fn PI() -> f64 { return 3.14159265358979323846; }
    fn E()  -> f64 { return 2.71828182845904523536; }

    // Absolute Value
    fn abs(x: f64) -> f64 {
        return c_math::fabs(x);
    }
    
    // Trigonometry
    fn sin(x: f64) -> f64 {
        return c_math::sin(x);
    }

    fn cos(x: f64) -> f64 {
        return c_math::cos(x);
    }

    fn tan(x: f64) -> f64 {
        return c_math::tan(x);
    }

    fn asin(x: f64) -> f64 {
        return c_math::asin(x);
    }

    fn acos(x: f64) -> f64 {
        return c_math::acos(x);
    }

    fn atan(x: f64) -> f64 {
        return c_math::atan(x);
    }

    fn atan2(y: f64, x: f64) -> f64 {
        return c_math::atan2(y, x);
    }

    // Exponentials and Logarithms
    fn sqrt(x: f64) -> f64 {
        return c_math::sqrt(x);
    }

    fn pow(base: f64, exp: f64) -> f64 {
        return c_math::pow(base, exp);
    }

    fn exp(x: f64) -> f64 {
        return c_math::exp(x);
    }

    fn log(x: f64) -> f64 {
        return c_math::log(x);
    }

    fn log10(x: f64) -> f64 {
        return c_math::log10(x);
    }

    // Rounding and Remainder
    fn ceil(x: f64) -> f64 {
        return c_math::ceil(x);
    }

    fn floor(x: f64) -> f64 {
        return c_math::floor(x);
    }

    fn round(x: f64) -> f64 {
        return c_math::round(x);
    }

    fn mod(x: f64, y: f64) -> f64 {
        return c_math::fmod(x, y);
    }

    // Min/Max
    fn max(a: f64, b: f64) -> f64 {
        return c_math::fmax(a, b);
    }

    fn min(a: f64, b: f64) -> f64 {
        return c_math::fmin(a, b);
    }
}
